ListenPort: ":8099"

# Dingtalk 群机器人 access_token
Dingtalk:
  P0: token...
  P1: token...
  P2: token...
  P3: token...

# 云片电话报警
PhoneCall:
  apikey: key...

# 微信消息 token
Weixin:
  P0: token...
  P1: token...
  P2: token...
  P3: token...

Telegram:
  bot_token: token...
  P0: chat_id
  P1: chat_id
  P2: chat_id
  P3: chat_id

# 值班人员信息-数据库
DataBase:
  host: db_host...
  port: "7531"
  username: root
  password: pwss...
  database: infrastructure
  table: oncall_users

# 检查的服务
Checks:
  prometheus: http://url...
  alertmanager: http://url...
