# 值班人员信息-数据库
DataBase:
  host: db_host...
  port: "7531"
  username: root
  password: pwss...
  database: infrastructure
  table: oncall_users

# Dingtalk 群机器人 access_token
Dingtalk:
  P0: token...
  P1: token...
  P2: token...
  P3: token...

# 云片电话报警, 即将遗弃的配置
PhoneCall:
  apikey: key...
# 云片短信+语音
yunpian:
  apikey: aaa333aaa333...
  sms:
    mobile:
      p0: 15711097086,15711097086
      p1: 15711097086
      p2:
      p3:
    tpl_id: 5452960
  voice:
    mobile:
      p0: 15711097086,15711097086
      p1: 15711097086
      p2:
      p3:

# 微信消息 token
Weixin:
  P0: token...
  P1: token...
  P2: token...
  P3: token...

Telegram:
  bot_token: token...
  P0: chat_id
  P1: chat_id
  P2: chat_id
  P3: chat_id

# 检查的服务
Checks:
  prometheus: http://url...
  alertmanager: http://url...
